name: Build and run tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release
